# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date playing')),
                ('approvedBookingBoss', models.BooleanField(default=False)),
                ('approvedManager', models.BooleanField(default=False)),
                ('technicalRequirements', models.CharField(max_length=100)),
                ('pris', models.DecimalField(decimal_places=2, max_digits=30)),
                ('technicians', models.CharField(default='hei', max_length=200)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpro.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpro.Scene'),
        ),
    ]
