# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0004_bandinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandinfo',
            name='band',
        ),
        migrations.AddField(
            model_name='band',
            name='StreamCount',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='band',
            name='Visits',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='BandInfo',
        ),
    ]
