# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0007_merge_20171003_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pris',
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticketPrice',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
