# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0008_auto_20171003_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='Genre',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='band',
            name='StreamCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='Visits',
            field=models.IntegerField(default=0),
        ),
    ]
