# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0002_auto_20171004_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='startDate')),
                ('endDate', models.DateField(verbose_name='endDate')),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='bandName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
