# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0004_booking_songs'),
        ('fpro', '0004_booking_review'),
    ]

    operations = [
    ]
