# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0004_auto_20170927_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StreamCount', models.CharField(max_length=250)),
                ('Visits', models.CharField(max_length=500)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpro.Band')),
            ],
        ),
    ]
