# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0005_merge_20171024_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pressLink',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
