# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0005_merge_20171024_1238'),
        ('fpro', '0005_merge_20171023_2349'),
    ]

    operations = [
    ]
