# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0006_booking_presslink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='review',
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='_booking_review_+', to='fpro.Booking'),
        ),
    ]
