# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0006_auto_20171003_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='StreamCount',
            field=models.CharField(default='', max_length=250),
        ),
    ]
