# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0007_merge_20171003_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pris',
        ),
        migrations.AlterField(
            model_name='band',
            name='StreamCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='Visits',
            field=models.IntegerField(default=0),
        ),
    ]
