# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0007_auto_20171024_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='review',
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
