# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0008_auto_20171024_2246'),
        ('fpro', '0005_merge_20171019_1141'),
    ]

    operations = [
    ]
