# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0009_merge_20171025_0807'),
        ('fpro', '0006_merge_20171024_1501'),
    ]

    operations = [
    ]
