# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0009_merge_20171025_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='techAtt',
            field=models.CharField(blank=True, default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='techUnatt',
            field=models.CharField(blank=True, default='[]', max_length=1000),
        ),
    ]
