# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0010_merge_20171025_1030'),
        ('fpro', '0010_auto_20171025_1133'),
    ]

    operations = [
    ]
