# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0011_auto_20171004_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='Genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fpro.Genre'),
        ),
    ]
