# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpro', '0011_merge_20171025_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completedTechnicalRequirements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
